version: '3'

services:
  nginx_server:
    build: ./nginx
    restart: always
    container_name: nginx_server
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - static:/usr/src/app/staticfiles
      - media:/usr/src/app/mediafiles
    depends_on:
      - django_web
  db:
    restart: always
    image: postgres
    container_name: charity_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  django_web:
    build: ./src
    restart: always
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate &&  python3 manage.py collectstatic --noinput && gunicorn project.wsgi:application -w 2 -b :8000 --reload"
    container_name: django_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static:/usr/src/app/staticfiles
      - media:/usr/src/app/mediafiles
    env_file:
      - ./src/.env

volumes:
  static:
  media:
  pgdata: